// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Keep your hardcoded fallbacks (generated), but also expose env-driven values
// so other modules (like the image proxy helper) can safely import the URL.
export const SUPABASE_URL =
  (import.meta.env?.VITE_SUPABASE_URL as string) ??
  "https://zcjzeafelunqxmxzznos.supabase.co";

export const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY as string) ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjanplYWZlbHVucXhteHp6bm9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NzE4MTgsImV4cCI6MjA2NDM0NzgxOH0.l0RObyMQCw23tmPfi5Wy7CgdmER93GYbR7IVPakzn-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
