name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://cli.supabase.com/install.sh | sh

      - name: Deploy updatelivepanda function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          PANDA_SCORE_API_KEY: ${{ secrets.PANDA_SCORE_API_KEY }}
        run: |
          supabase functions deploy updatelivepanda
