name: Trigger pandascoreplayers daily at 15:20 UK time

on:
  schedule:
    - cron: '20 14 * * *'  # 15:20 UK time
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger fetch_players function
        run: |
          curl -X POST https://zcjzeafelunqxmxzznos.functions.supabase.co/pandascoreplayers \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_FUNCTION_SECRET }}"
