name: Sync PandaScore Matches

on:
  workflow_dispatch:       # Manual trigger
  schedule:
    - cron: '*/5 * * * *' # Every 6 hours, adjust as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    env:  # 👈 Environment variables injected for use in the shell
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_FUNCTION_SECRET: ${{ secrets.SUPABASE_FUNCTION_SECRET }}

    steps:
      - name: Call Supabase Edge Function to sync matches
        run: |
          echo "Calling: ${SUPABASE_URL}/functions/v1/pandascorematches"

          RESPONSE=$(curl -s -X POST \
            "${SUPABASE_URL}/functions/v1/pandascorematches" \
            -H "Authorization: Bearer ${SUPABASE_FUNCTION_SECRET}" \
            -H "Content-Type: application/json")

          echo "Response:"
          echo "$RESPONSE"
